name: Promote a member to team maintainer

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'GitHub User Name'
        required: true
      team:
        description: 'GitHub Team Name'
        required: true

jobs:
  promote-member-to-team-maintainer:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      ImageOS: ubuntu20
    steps:
      - uses: chaspy/github-action-promote-member-to-team-maintainer@v1
        with:
          github_token: ${{ secrets.TEST_PROMOTE_MEMBER_ACTION}}
          user: ${{ github.event.inputs.user}} 
          team: ${{ github.event.inputs.team }}
